# This is a basic workflow to help you get started with Actions

name: Third party lib tester

# Controls when the workflow will run
on:

  schedule:
    - cron: '20 0 * * 6'  # saturday at midnight

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: master
          
      - name: Git Submodule Update Boring SSL
        run:
          git submodule update --remote transports/http3-quiche/third_party/boringssl/src
      
      - name: Git Submodule Update quiche
        run:
          git submodule update --remote transports/http3-quiche/third_party/quiche

      - name: Git Submodule Update zlib
        run:
          git submodule update --remote transports/http3-quiche/third_party/zlib
          
      - name: Git Submodule Update googleurl
        run:
          git submodule update --remote transports/http3-quiche/third_party/googleurl
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: thirdpartylibtracker
          delete-branch: true
          title: "Automated update of thirdparty libraries"
          body: "Automated changes by thirdparty libraries tracker GitHub action"
